### ISSUE TITLE
Fail on downloading log from cloud

### ISSUE THREAD

**Issue by g0vgs** [DorsetDevStudio/station-master-2-updates#1]
Welcome to Station Master 2 ** This is a PREVIEW version, please DO NOT report bugs directly, use the BUG REPORTING TOOL **

07/04/2024, 06:47:59: Importing Log from Cloud, going back all days.
07/04/2024, 06:47:59: Downloading log from cloud...
07/04/2024, 06:47:59: Error processing download or writing file:
07/04/2024, 06:49:00: Importing Log from Cloud, going back all days.
07/04/2024, 06:49:00: Downloading log from cloud...
07/04/2024, 06:49:00: Error processing download or writing file:

MacBook Air, 2020.  M1 chip

Ian

**Comment by g0vgs** [comment]
This was because the API didn't populate after logging into the cloud.  I entered it manually and I could then download my logs

Ian

**Comment by DorsetDevStudio** [comment]
> This was because the API didn't populate after logging into the cloud. I entered it manually and I could then download my logs
> 
> Ian

yep is doesn't auto populate the api key (yet), in the meantime, i'll make it output the actual reason for the failure.
