### ISSUE TITLE
CW mode not recognised

### ISSUE THREAD

**Issue by db3mi** [DorsetDevStudio/station-master-2-updates#11]
sm2 today's macos version: 101mp does not switch to cw (stays in ssb mode if you click cw station) and sm2 does not recognise cw mode - have to set it manually. rigcontrol via flrig. flrig itself seems to "know" cw (shown as cw-u)

73 de bemi, db3mi

**Comment by DorsetDevStudio** [comment]
hey Bemi, I've made a few updates, can you try it again.

note it won't select CW when clicking a CW cluster spot on the left, i will fix that soon.

Thanks
Stuart

**Comment by db3mi** [comment]
hi Stu,



sorry - still not working. Maybe it's a problem that the mode in the 
101mp and in flrig is called CW-U?

fb es tnx de db3mi, bemi

**Comment by DorsetDevStudio** [comment]
Hey Bemi, is still an issue ?

**Comment by db3mi** [comment]
Hey Stu,

it does not auto select cw but it stays. That's great.

tnx es 73
bemi

**Comment by DorsetDevStudio** [comment]
ok I'll leave it at that for now, cheers Bemi.
