### ISSUE TITLE
Map: locations on search from log

### ISSUE THREAD

**Issue by PaulG6NMA** [DorsetDevStudio/station-master-2-updates#12]
Hi Stu great work and would like to help on the testing.... 
Trying SM 2 out found some strange issues, could not find any pre reported issues as per this one.  
When clicking on search from log and call sign is located england defaults to location as london, Europe ireland wales and scotland all return correct locations. this also happens if call is entered and click go map appears. 
![map if england call always london](https://github.com/DorsetDevStudio/station-master-2-updates/assets/168172978/8bc21331-4c0d-479e-9745-3c5ae6b0dca9)
![ei ok on map](https://github.com/DorsetDevStudio/station-master-2-updates/assets/168172978/e5f502ef-c62a-4152-a7fd-fc48a59c5632)
Best regards
Paul G6NMA

**Comment by DorsetDevStudio** [comment]
hi, sorry I thought i'd replied to this. This is not a bug, you need to enter your QRZ username and password and tick "enable qrz name lookup" in settings, as well as have a qrz sub for the map to locate people correctly, Without a qrz sub it will only give you the country (capital)
