### ISSUE TITLE
Edit QSO time when entering new manual log

### ISSUE THREAD

**Issue by PaulG6NMA** [DorsetDevStudio/station-master-2-updates#13]
Add new log for QSO to SM2 log, QSO happend day before, transfer QSO from paper log to SM2 log  
Situation: Rig not connected to PC, Rig control off, PC conneted to internet. Operating system Win 10 version 22H2, 

Added in Call sign, frequency mode... no viable way to add in QSO time.  added Log. time stamped with time of entry. 
went to log book tab, found QSO and clicked on edit, no box to edit or add in QSO time. see pic.

to fix issue: entered QSO in SM1 and the imported from Cloud to SM2, logs now in SM2 with correct times. (notes time are GMT,  log entered in SM1 was UTC)  Log ID seems to be out of sync after import.

 
![import from cloud](https://github.com/DorsetDevStudio/station-master-2-updates/assets/168172978/6ede4293-0817-4039-b91f-8618e1d37a66)
![adf import from sm1 to cloud then sync cloud sm2](https://github.com/DorsetDevStudio/station-master-2-updates/assets/168172978/98133668-3674-4d3f-bd46-c0ba0ab1108c)
![import from cloud all qso on the 25_04_2024](https://github.com/DorsetDevStudio/station-master-2-updates/assets/168172978/61346c05-3d93-4138-a515-69d1f75ed891)
Paul G6NMA

**Comment by DorsetDevStudio** [comment]
I think this is resolved, feel free to open another issues if there is still a problem, thanks.
