### ISSUE TITLE
SM2 Desktop Mac version - ADIF Import

### ISSUE THREAD

**Issue by DuncanGM5JET** [DorsetDevStudio/station-master-2-updates#14]
When importing an ADIF file in the Mac version, SM2 does not pickup and display the Country entries in the SM log.

**Comment by DorsetDevStudio** [comment]
Hi @DuncanGM5JET can you send me the adif file you are using please so i can test.

You can click **_Maintenance > Clean Contact Log_** and it should fill any missing DXCC/ Countries.

**Comment by DuncanGM5JET** [comment]
Hi Stu,

No bother, ADIF is attached.

Interestingly, having clicked Clean Contact Log, the countries are still blank in my SM2 log as are my DXCC’s, which report "You've worked 144 of 0 DXCCs, that's Infinity%”

Thanks again for all the work on this.

All the best,
Duncan GM5JET

￼

**Comment by DorsetDevStudio** [comment]
Thanks, sounds like your installation has not been able to create a local DXCC database.  IT should say "of 340" DXCCs.

I'll do some testing.

**Comment by DorsetDevStudio** [comment]
ok @DuncanGM5JET I've fixed the issue where the DXCC list is empty, that should fill up after you install the latest updates, it may take a minute to populate, if it does not show 340 DXCCs then restart SM again and allow it a minute to refresh itself in the background.

After that is working run the maintenance and it will assign DXCCs to the contacts.

I'll do some further testing with your file to tomorrow to see if there was a separate issue there too.

Thanks
Stuart
