### ISSUE TITLE
QTH field not populated with QRZ data pull or on refresh

### ISSUE THREAD

**Issue by DuncanGM5JET** [DorsetDevStudio/station-master-2-updates#16]
Carried forward from Discord, the QTH field in the logbook is not populated in the Mac version with QRZ city data on data pull or on refresh.  Is this something that can be incorporated as there is no QTH/City field entry to the log except by editing once the log entry has been made.

**Comment by DorsetDevStudio** [comment]
Hi Duncan this is now in place and ready to test
