### ISSUE TITLE
Frequency display

### ISSUE THREAD

**Issue by Russyb1** [DorsetDevStudio/station-master-2-updates#19]
Hi the Frequency display in sm2 does not follow the radio for me.

**Comment by DorsetDevStudio** [comment]
Hi Russ, I'll need more information please. What cat control settings are you using please.

**Comment by Russyb1** [comment]
Hi Stu, So I have an icom ic-7300 and ic7000, both work fine on sm1 with
omni-rig but on sm2 they are connected because I can change modes and freq
if I click a cluster spot but the reading on the software doesn't follow
the rig. However if i connect the rig direct it all works fine, I like to
use omni-rig though because I like to do lots of digital work.

Thanks Russ

**Comment by DorsetDevStudio** [comment]
Hey Russ, I know it's been a while, I have made update to the Omrig integration yesterday, it may resolve your problems. Please download the latest version and try again. You will need to select RIG 1 or RIG 1 in SM2 settings.

**Comment by Russyb1** [comment]
Hi Stu, Unfortunately not on either rig. I have the 7300 on rig 1 and the
7000 on rig 2 both work fine in SM1 but not SM2.

Russ

**Comment by DorsetDevStudio** [comment]
Ok Russ, I'll keep working on it, can you try setting the poll rate to a higher number in omnirig, it's normally about 100-250 (ms) , increate that to 500 - 1000, that will slow it down and may solve the issue.

**Comment by Russyb1** [comment]
Ok so changing the poll rate did nothing, however I have noticed that sm2
reads the mode and I can change the mode from the software, also if I click
a cluster spot it will take the rig to that freq but still no freq tracking
from the rig on the software.

**Comment by DorsetDevStudio** [comment]
fixed
