### ISSUE TITLE
Rig Control Error

### ISSUE THREAD

**Issue by g0vgs** [DorsetDevStudio/station-master-2-updates#2]
Got a problem with rig control.  Flrig sees the radio and works as expected.  If I start rig control then in SM, I get this...  I am using a serial device to my radio, not TCPIP

<img width="258" alt="Screenshot 2024-04-07 at 09 51 34" src="https://github.com/DorsetDevStudio/station-master-2-updates/assets/83948259/09014c30-0725-488c-aaec-496bfea88999">

**Comment by DorsetDevStudio** [comment]
hi @g0vgs , please ensure FLRIG is selected as the RIG Control type in settings, thanks. The error suggests you have another option selected. 
Stuart

**Comment by g0vgs** [comment]
Bingo.  I left it at serial as I thought that was what I was doing.  My bad, sorry

Ian
