### ISSUE TITLE
DX Cluster not working when i changed the settings

### ISSUE THREAD

**Issue by G7NFK** [DorsetDevStudio/station-master-2-updates#20]
Hi Stu.
I changed the telnet settings in the cluster setup and it would't connect so changed them back to original setting and still not connecting.
The reason for swapping the cluster was the origanal one wasn't posting spots I made but it told me it had posted them .
Thanks Stu 
EA5JMN Jon

**Comment by DorsetDevStudio** [comment]
I'm just deploying an update that will make the spotting work,
