### ISSUE TITLE
lost of log book

### ISSUE THREAD

**Issue by FunnyHand** [DorsetDevStudio/station-master-2-updates#21]
Hi Stu,
After doing the last update I have lost all my contacts in SM 2 just a blank page, I still have them in ST1. I have tried to pull them down form the cloud but did not work, copied them over and tired to import them still a blank screen.
have you any ideas please.

Thanks
Peter
2E0FPH

**Comment by DorsetDevStudio** [comment]
Hi Peter, please make sure you have `show all` selected.

![image](https://github.com/DorsetDevStudio/station-master-2-updates/assets/39198208/38b4eb79-3ebd-4d85-ae79-9ec59e6b1c23)

**Comment by DorsetDevStudio** [comment]
done
