### ISSUE TITLE
Beam azimuth 

### ISSUE THREAD

**Issue by tribe42-ws** [DorsetDevStudio/station-master-2-updates#22]
Hi Stu, 

after the update yesterday, the beam azimuths seem to be incorrect in the map tab?

![SM2_Map](https://github.com/DorsetDevStudio/station-master-2-updates/assets/174232245/828f6671-4520-475c-87e7-958fe024beec)

keep up the great work
Wayne (2E0WZW)

**Comment by DorsetDevStudio** [comment]
Hey Wayne, so it is. I'll get that fixed this shortly.

**Comment by tribe42-ws** [comment]
Hi Stu, just and observation, I'm certain you would have spotted it :)   not a show stopper at all.    only so many hours in a day, with your day job and SM.

**Comment by DorsetDevStudio** [comment]
I'm glad you reported it as I hasn't noticed yet. It's fixed now, the update will be live in the next hour or so. Cheers

**Comment by DorsetDevStudio** [comment]
done
