### ISSUE TITLE
Location of UK Stations not showing correctly

### ISSUE THREAD

**Issue by m0scs** [DorsetDevStudio/station-master-2-updates#24]
Hi Stu
Ive been using SM2 for a couple of days and I've noticed that a lot of UK Stations are not being plotted correctly on the Map screen and defaulting to IO91WM square in London. Is there a setting I need to alter so it shows correctly?

I've had no issues with SMv1 and have checked and the stations info does show their location square correctly.

Thanks
Simon

<img width="517" alt="SM2 Map view location issue" src="https://github.com/user-attachments/assets/d3314510-3ac9-4080-b676-28c390caa9d9">

**Comment by DorsetDevStudio** [comment]
Hi Simon, it looks like to you either haven't enabled QRZ name lookup in setting, or enter your qrz user name or password incorrectly.

Hope that helps
Stu

**Comment by m0scs** [comment]
Hi Stu

I updated to the latest version and re entered the api, QRZ login etc and
now seems to be all good.

Thanks

Simon
