### ISSUE TITLE
NO audio MP3 since current update

### ISSUE THREAD

**Issue by VK2LQ** [DorsetDevStudio/station-master-2-updates#26]
Hi All

I hope all are well, I just updated to version 2.2.23 no I have lost all mp3 audio I now get (error accessing media devices) worked b4 the upgrade

I still am unable to select audio device input out output in settings  the laptop I have been using has Realtek sound card/drivers

The radio connected is an FTdx1010MP via USB

**Comment by DorsetDevStudio** [comment]
is this still an issue ?

**Comment by VK2LQ** [comment]
Sorry I thought I posted this issue was resolved a few updates back 👍 👍 👍 

⁣Get BlueMail for Android ​

**Comment by DorsetDevStudio** [comment]
thanks
