### ISSUE TITLE
Rig frequency Not Updating on SM Cloud or SM2 Frequency Window (FT-891)

### ISSUE THREAD

**Issue by irishhamradio** [DorsetDevStudio/station-master-2-updates#28]
Using OmniRig 1 (same as what I use for SM 1).
- Able to set frequency on radio by entering it into the frequency window and pressing enter.
- Able to set frequency on radio by clicking on spots.
- SM2 Frequency Window does not update when I tune dial on radio.
- SM Cloud has my frequency as 0.00 at all times.

**Comment by DorsetDevStudio** [comment]
Hi Dave, are you about tomorrow evening, I can take a look and see what's going on.

**Comment by irishhamradio** [comment]
Hi Stu,
Yep, should be hopefully.
Just drop me a WhatsApp if that's easiest to arrange.
I'm back over to SM 1 now anyway... Not sure if its something I've done wrong, but its like rig control is only working in one direction (from SM to rig, but not from rig to SM).

**Comment by DorsetDevStudio** [comment]
moving to hamlib solved it
