### ISSUE TITLE
Call Sign Not Logging When Fowarding from WSJT-X

### ISSUE THREAD

**Issue by hdjmings1** [DorsetDevStudio/station-master-2-updates#29]
Hi stu M0KNM Martin here when a log is made in wsjt-x it does not log the call sign only mine 3 contacts made 29-08-24 all with no call sign
![Screenshot 2024-08-29 234022](https://github.com/user-attachments/assets/2baa8ba8-2638-440e-9f4f-62ec0a3c14c5)

top 3 is done via station master 2 and bottom contact is via station master 1

**Comment by hdjmings1** [comment]
have a got a setting wrong?

**Comment by DorsetDevStudio** [comment]
how are you integrating that? vis the desktop app or direct to the cloud from wsjtx ?

**Comment by hdjmings1** [comment]
Via the desktop app, sends it via the UDP server port 2237 if i remember right, I've tried opening WSJTX via station master and it does the same

**Comment by DorsetDevStudio** [comment]
it's port 2333, please ensure you have these options set too, cheers.
![image](https://github.com/user-attachments/assets/c10beb42-1108-4701-bc61-c34d1f2443ec)

**Comment by hdjmings1** [comment]
done that mate it now comes up with it but it logs it twice. i think it has something to do with another program as i use JTAlart and Gridtracker with it.
JTAlart needs the top UDP server to function but it logs the qso too so think it might be this.

![Screenshot 2024-08-31 010603](https://github.com/user-attachments/assets/a6c0c357-d3cd-4f6a-946f-84db6e717265)

**Comment by DorsetDevStudio** [comment]
ok, I'll add some extra dupe checking, but you need to make sure you don't have two programs sending the contacts to station master. Cheers.
