### ISSUE TITLE
Import Log from cloud or local adif

### ISSUE THREAD

**Issue by KJ5AJB** [DorsetDevStudio/station-master-2-updates#3]
Get the following error when trying to import log from cloud.

4/7/2024, 8:08:36 AM: Importing Log from Cloud, going back all days.
4/7/2024, 8:08:36 AM: Downloading log from cloud...
4/7/2024, 8:08:36 AM: Error processing download or writing file:

**Comment by KJ5AJB** [comment]
This is the Mac OS version

**Comment by DorsetDevStudio** [comment]
@KJ5AJB please enter your "Sm Cloud Api Key" into the settings. You can get it from your cloud account in the website.  I will make the error clearer in a future update.

Thanks

**Comment by DorsetDevStudio** [comment]
please leave this issue open so others can see it. I'll close it when i have deployed an update.
Thanks

**Comment by KJ5AJB** [comment]
That fixed it.
Thanks
