### ISSUE TITLE
Lock Time

### ISSUE THREAD

**Issue by tribe42-ws** [DorsetDevStudio/station-master-2-updates#33]
Hi Stu, 

Not a bug, more a nice to have in my OCD world.  could the Time lock and the boxes be hidden like Their ref input boxes.  with an icon on the side? 

Just the logging box section is getting very cluttered  

keep up the great work :) 

73's
Wayne
2E0WZW

**Comment by DorsetDevStudio** [comment]
Will do Wayne, working on it now. Thanks.

**Comment by tribe42-ws** [comment]
Thanks Stu, it not show stopper.  just bakes my OCD brain LOL

**Comment by tribe42-ws** [comment]
perfect thanks Stu :) 
![sm2](https://github.com/user-attachments/assets/7d694bc4-17ae-4f35-aed2-7d057ae0c188)
Just one slight glitch, the pop box is also hiding with the time.
