### ISSUE TITLE
Greyline is now showing reversed

### ISSUE THREAD

**Issue by m0scs** [DorsetDevStudio/station-master-2-updates#35]
Hi Stu

Not sure when this happened but the Grey line is now showing the wrong way round so the grey area is now showing over the the area in daylight and vice versa!

![image](https://github.com/user-attachments/assets/27c404b4-e3fb-4ac2-b87d-b8cfa6ee30eb)

This was taken at 17:41 

I tried deselecting greyline and switching it on again but its still the same.

Thanks

Simon M0SCS

**Comment by DorsetDevStudio** [comment]
HahaThanks I'll have a look in a moment.StuSent from my Commodore Amiga 500On 23 Sep 2024, at 17:43, m0scs ***@***.***> wrote:﻿
Hi Stu
Not sure when this happened but the Grey line is now showing the wrong way round so the grey area is now showing over the the area in daylight and vice versa!
image.png (view on web)
This was taken at 17:41
I tried deselecting greyline and switching it on again but its still the same.
Thanks
Simon M0SCS
