### ISSUE TITLE
WSJT-X Live map update

### ISSUE THREAD

**Issue by M7VMT** [DorsetDevStudio/station-master-2-updates#39]
Running IC-7300 through Omni-Rig. WSJT-X Ver 2.7.1-devel 240510 all ports open. Unable to see 'Live' tracking on maps but logging prompt on completion of QSO.
Is live mapping live on released version?

**Comment by DorsetDevStudio** [comment]
Thanks for reporting, I am investigating. Will post a response here.

**Comment by DorsetDevStudio** [comment]
This is resolved, thanks.
