### ISSUE TITLE
option to close map info box

### ISSUE THREAD

**Issue by garyM7FHJ** [DorsetDevStudio/station-master-2-updates#4]
Hi Stu

Hope. you are well and great news with the SM 2.0

One thing we used to have was an option to close the image box down on the map as per the pic attached. it may just be me but after seeing the person I do like to learn where other hams are on the maps location by zooming in and so on.

Hope that all makes sense 

Gary

<img width="1125" alt="Screenshot 2024-04-08 at 00 35 52" src="https://github.com/DorsetDevStudio/station-master-2-updates/assets/166343478/d450c2e7-1ea6-40d7-a739-c52dc7922f56">

**Comment by DorsetDevStudio** [comment]
done
