### ISSUE TITLE
missing date and time in logbook

### ISSUE THREAD

**Issue by MickeyRedEyes** [DorsetDevStudio/station-master-2-updates#5]
<img width="786" alt="image" src="https://github.com/DorsetDevStudio/station-master-2-updates/assets/85794947/7a0962da-8fdb-4287-aa03-f9264d785fc5">

Hi hi
The date and time of qso is not recording on logbook, or not displayed

**Comment by MickeyRedEyes** [comment]
Refresh 'cures' it

**Comment by DorsetDevStudio** [comment]
Hi, this is a known bug I'll fix it soon. if you click the title it will change to UTC which will auto update, else click refresh.
leave this open and I'll close this issue once fixed.
Thanks for reporting.

**Comment by DorsetDevStudio** [comment]
fixed in latest version
