### ISSUE TITLE
local time entries.

### ISSUE THREAD

**Issue by Lensteruk** [DorsetDevStudio/station-master-2-updates#6]
The log does not show the local time during entry, hitting refresh shows the data has actually been entered - display issue not a data issue.

**Comment by Lensteruk** [comment]
Just noticed I am on 2.103 so will update and check this issue persists.

**Comment by DorsetDevStudio** [comment]
hi @Lensteruk thanks for reporting this is a know issue so i'll close this issue as it's already over here #5

**Comment by Lensteruk** [comment]
updated and the issue still persists.. clicking refresh updates the entry so not a major issue.
