### ISSUE TITLE
Map - on first click does not fill to window size

### ISSUE THREAD

**Issue by Lensteruk** [DorsetDevStudio/station-master-2-updates#8]
Minor bug.  When first clicked, the map does not expand to fill the window.  Resizing window renders the full image into the frame.
![Screenshot 2024-04-08 at 21 43 20](https://github.com/DorsetDevStudio/station-master-2-updates/assets/36043994/f6aa9f9b-fd13-4008-9069-d3446bc9ab8e)

**Comment by DuncanGM5JET** [comment]
Just for bug tracking, I am also still experiencing this issue on the latest Mac version.

**Comment by DorsetDevStudio** [comment]
done
