### ISSUE TITLE
13" MacBook layout needs attention.

### ISSUE THREAD

**Issue by DorsetDevStudio** [DorsetDevStudio/station-master-2-updates#9]
Ability to hide/resize left panel without losing the freq box

**Comment by MickeyRedEyes** [comment]
A nice  workaround is Settings>Displays>"More Space"
This  increases resolution. 
<img width="711" alt="image" src="https://github.com/DorsetDevStudio/station-master-2-updates/assets/85794947/a75d27da-ea11-409f-8f36-fae2cf4aa84e">
